### ISSUE TITLE
테스트 결과 입력 -> 코멘트 내용 기입 시 다른 체크리스트 이동해도 초기화되지 않음

### ISSUE THREAD

**Issue by bourbonkk** [case-book/casebook#106]
사용자 WEB에 코멘트를 적고 
![image](https://github.com/case-book/casebook/assets/25188468/e789232e-834c-4d17-adf9-833202cced77)

다른 체크리스트로 넘어가도 그대로 코멘트가 존재함
![image](https://github.com/case-book/casebook/assets/25188468/0e31059e-24c4-4992-8f86-2a60ff645104)

**Comment by mindplates** [comment]
@bourbonkk 
제보 감사합니다. 
v1.3.2버전에서 조치(#107)되었습니다.
