### ISSUE TITLE
로그인 화면의 모달 창에서 엔터를 누르면 다시 로그인 버튼이 눌리는 문제

### ISSUE THREAD

**Issue by scintillavoy** [case-book/casebook#109]
### 재현 방법
- 로그인 화면에서 잘못된 사용자 정보를 입력하고 로그인 버튼을 클릭.
- "일치하는 사용자 정보가 없습니다."라는 메시지의 모달 창이 떴을 때 키보드로 엔터 키 입력.
- 모달 창이 닫히자마자 로그인 버튼을 누른 것으로 인식되며 모달 창이 다시 뜸.

**Comment by mindplates** [comment]
@scintillavoy 
제보 감사합니다! 
#123 을 통해 수정되었으며, v1.3.5 버전에 포함되어 릴리즈될 예정입니다.

**Comment by mindplates** [comment]
@kakao-kevin-12 
v1.3.5 버전이 릴리즈되었습니다.
