### ISSUE TITLE
테스트런 테이스케이스 검색 기능 강화

### ISSUE THREAD

**Issue by kakao-kevin-12** [case-book/casebook#121]
테스트런의 테스트케이스 선택 기능이 전체 목록에서 하나씩 보면서 선택하는 방법밖에 제공되지 않아서 특정 상황에서 불편한 점들이 있습니다.
아래 제안한 태그나 버전 등의 기능으로 선택하거나, 혹은 테스트케이스의 생성된 날짜나 수정된 날짜를 통해서 검색하거나, 선택 하는 기능이 있다면 더 편리하게 테스트런을 생성할 수 있을 것 같습니다.

**Comment by kakao-davi-d** [comment]
프로젝트 명으로 검색하는 기능도 있으면 좋을 것 같습니다.

**Comment by mindplates** [comment]
[v2.0.0](https://github.com/case-book/casebook/releases/tag/v2.0.0) 에서 추가되었습니다.
