### ISSUE TITLE
스페이스 참여 요청 404 오류

### ISSUE THREAD

**Issue by kakao-kevin-12** [case-book/casebook#124]
![image](https://github.com/case-book/casebook/assets/141005184/5c162f14-1be0-47d3-acb5-8d94d0f591db)

스페이스 참여 요청을 누르면, 404 오류가 발생하고 참여 요청이 정상적으로 진행되지 않습니다.

**Comment by mindplates** [comment]
해당 오류 #126에서 수정되었으면, v1.3.5 릴리즈에 포함되어 배포될 예정입니다.

**Comment by mindplates** [comment]
@kakao-kevin-12 
v1.3.5 버전이 릴리즈되었습니다.
