### ISSUE TITLE
스페이스 참여 요청/참여 요청 취소 알림 배지 변경 안되는 오류

### ISSUE THREAD

**Issue by kakao-kevin-12** [case-book/casebook#125]
스페이스 참여 요청 및 취소 정보 등이 실시간으로 알림 배지로 알림이 오는 것으로 알고 있는데, 현재 요청/취소 정보가 등록되어도 알림 배지가 실시간으로 전달이 되지 않는 것으로 보입니다. (화면을 새로고침하면, 그때 배지의 카운트가 변경됩니다.)

**Comment by mindplates** [comment]
해당 오류 #126에서 수정되었으면, v1.3.5 릴리즈에 포함되어 배포될 예정입니다.

**Comment by mindplates** [comment]
@kakao-kevin-12 
v1.3.5 버전이 릴리즈되었습니다.
