### ISSUE TITLE
request feature of comment for ended testrun

### ISSUE THREAD

**Issue by dreamiiizer** [case-book/casebook#128]
Hello.

Is it possible to add additional information related to the results or the ability to input data such as comments to the finished test run?
since there is no function to terminate the testrun and add any function to that test run,
it is inconvenient because I have to take notes on the test run or record it separately from the casebook.

thank you.

**Comment by mindplates** [comment]
layout of the report detail page has been changed and we added a feature that allows to view and create comments on the report detail page. this feature will be added to the v1.3.4(#130) release.
thank you.

**Comment by mindplates** [comment]
@dreamiiizer 
v1.3.5 has been released.

**Comment by dreamiiizer** [comment]
thanks! 👍 👍
