### ISSUE TITLE
테스트케이스 조회 관련 개선사항

### ISSUE THREAD

**Issue by isangu** [case-book/casebook#138]
- 특정 테스트케이스에 대한 조회 링크를 첨부하고 싶은데, 그러한 링크가 없다보니 하이라이팅 한 채로 이동할 수 있는 앵커태그 등이 포함된 url 로 특정 프로젝트 내의 테스트케이스를 바로 조회할 수 있으면 좋을 것 같습니다. (TC111 등의 숫자를 누르면 해당 url 이 복사되면 좋을 것 같아요)

- 유사한 내용이지만, 특정 테스트케이스를 ctrl + F 로 검색해서 조회하기 보다는, 테스트케이스 제목 등이 포함된 항목들만 필터링해서 화면에 노출할 수 있도록 검색 기능이 있으면 좋겠습니다.

**Comment by mindplates** [comment]
- 테스트케이스 경로 선택 정보 URL 처리는 v1.3.6에 배포될 예정입니다. (https://github.com/case-book/casebook/pull/156)
- 나머지 기능은 v1.3.7 버전 백로그로 관리하겠습니다.

**Comment by mindplates** [comment]
[v2.0.0](https://github.com/case-book/casebook/releases/tag/v2.0.0) 에서 추가되었습니다.
