### ISSUE TITLE
테스트케이스 관련 기능 추가 건의

### ISSUE THREAD

**Issue by isangu** [case-book/casebook#139]
- 테스트케이스를 만들다보면, 테스트케이스간에 선후관계가 형성되는 경우가 종종 있는 것 같습니다. 마치 지라에서 blocked by 라던지 relates 라던지 테스트케이스간의 관계를 표현할 수 있는 기능이 있으면 좋을 듯 합니다.

**Comment by mindplates** [comment]
[v2.1.0 ](https://github.com/case-book/casebook/releases/tag/v2.1.0) 버전에서 케이스 간의 연결 관계를 설정할 수 있는 기능이 추가되었습니다. 현재는 테스트런의 케이스 포함 여부와 동일한 테스터 지정 기능으로 활용할 수 있습니다. 다음 버전 업데이트에서 선후 관계를 테스트 시에 활용 (순서대로 테스트 진행, 테스트케이스에서 연결된 테스트케이스 표시 및 이동 기능 등) 할 수 있도록 기능을 추가할 예정입니다.
