### ISSUE TITLE
프로젝트 별 변수 추가

### ISSUE THREAD

**Issue by again7536** [case-book/casebook#162]
Postman 처럼 프로젝트 단위에서 사용할 수 있는 변수가 있으면 좋을 것 같습니다.
예를 들어 특정 프로젝트에 개발/운영 페이즈가 있는 경우에, 현재는 테스트케이스마다 url을 2개 추가함으로써 각 페이즈 별 링크를 넣을 수 있습니다.
하지만 변수를 사용하여 해당 변수만 테스트런 생성 시에 바꿔줄 수 있다면, 각 테스트케이스에서는 1개 url (예컨대, `{{base_url}}/example/~~`)만 작성해도 될 것 같습니다.

**Comment by mindplates** [comment]
👍

**Comment by mindplates** [comment]
v1.5.0 버전에 스페이스 레벨에서의 변수가 추가되었습니다. 
프로젝트 레벨에서 변수는 추후 고민하여 추가할 예정입니다!
