### ISSUE TITLE
반복 테스트런 편집 후 저장 불가 이슈

### ISSUE THREAD

**Issue by bourbonkk** [case-book/casebook#184]
## 증상
테스트런에서 테스트 케이스를 추가 후 저장 시 오류 발생
<img width="1073" alt="image" src="https://github.com/case-book/casebook/assets/25188468/ddd3dbd6-bd33-4f92-976b-19478885e37d">
<img width="691" alt="image" src="https://github.com/case-book/casebook/assets/25188468/018e2207-9c5b-4da7-b497-5cb033d67e1f">

**Comment by mindplates** [comment]
v2.0.0 버전에서 수정되었습니다.

**Comment by mindplates** [comment]
[v2.0.0](https://github.com/case-book/casebook/releases/tag/v2.0.0) 에서 수정되었습니다.

**Comment by mindplates** [comment]
[v2.0.0](https://github.com/case-book/casebook/releases/tag/v2.0.0) 에서 수정되었습니다.
