### ISSUE TITLE
종료된 테스트런을 다시 종료할 수 있는 문제

### ISSUE THREAD

**Issue by scintillavoy** [case-book/casebook#83]
- 종료된 테스트런 정보 페이지의 우측 상단에 테스트런 종료 버튼이 있는데, 해당 버튼을 누르면 이미 종료된 테스트런을 다시 종료할 수 있는 문제가 있습니다.
- URI: `/spaces/${spaceCode}/projects/${projectId}/testruns/${testrunId}`

**Comment by mindplates** [comment]
종료된 테스트런에 대한 처리를 개선하였습니다. #88
