### ISSUE TITLE
테스트케이스를 다른 그룹으로 이동해도 테스트런에 반영되지 않는 문제

### ISSUE THREAD

**Issue by scintillavoy** [case-book/casebook#84]
- 어떤 테스트케이스로 테스트런을 만든 후, 해당 테스트케이스를 다른 테스트케이스그룹으로 옮겨도 테스트런 정보 페이지에는 기존 테스트케이스그룹에 속한 것으로 표시됩니다.

**Comment by mindplates** [comment]
@scintillavoy 
좋은 의견 감사합니다. 
다만 테스트런은 테스트런 생성 당시의 테스트케이스 구조를 복사하여, 만들어지게 됩니다. 테스트런이 생성된 이 후에 생성된 테스트케이스 그룹으로 이동되는 경우, 테스트런에는 새로 생성된 테스트케이스 그룹이 존재하지 않는 등의 예외적인 케이스에 대한 대응이 어려운 문제가 있습니다.
말씀하신 부분은 설계시에 미처 고려하지 못한 부분으로 시작된 구조적인 문제가 있어, 당분간은 수정이 어려울 것 같습니다. 추후에 테스트케이스와 테스트런과의 관계를 개선하면서 다시 고민해보도록 하겠습니다.

불편하시겠지만, 현재는 테스트그룹 및 케이스의 이동을 테스트런에 반영하려면, 테스트런을 다시 만들어주시면 감사하겠습니다.
