### ISSUE TITLE
연관된 테스트런이 있는 테스트케이스그룹을 삭제할 수 없는 문제

### ISSUE THREAD

**Issue by scintillavoy** [case-book/casebook#85]
- 테스트케이스그룹과 그 그룹에 속하는 테스트케이스를 만들고, 해당 테스트케이스로 테스트런을 만든 후
- 만들었던 테스트케이스그룹을 삭제하려고 하면 "알 수 없는 오류가 발생하였습니다."라는 메시지와 함께 삭제에 실패합니다.
- 테스트케이스그룹을 삭제할 때 테스트런과의 매핑 관계를 적절히 처리하지 않아서 발생하는 문제인 것 같습니다.

**Comment by mindplates** [comment]
@scintillavoy 
제보 감사합니다!
테스트케이스/테스트케이스 그룹/테스트런 삭제 시 참조되는 테스트런 관련 데이터로 인해 삭제되지 않고, 에러가 발생하는 오류를 수정하였습니다. #92 
추가적으로 테스트런의 결과 모수가 업데이트 되지 않는 오류가 있는데, 이 부분도 곧 수정하도록 하겠습니다!
