### ISSUE TITLE
일부 페이지에서 권한이 없는 프로젝트 이름이 노출되는 문제

### ISSUE THREAD

**Issue by scintillavoy** [case-book/casebook#97]
- `/spaces/{spaceName}/projects`에서는 권한이 있는 프로젝트 목록만 노출됩니다 (정상 작동).
- `/spaces/{spaceName}/projects/{projectId}`에서는 GNB 우측에 현재 프로젝트 이름이 표시되는데, 해당 부분을 눌렀을 때 나오는 드롭다운 메뉴에서는 권한이 없는 프로젝트도 노출됩니다.
- `/spaces/{spaceName}/info` 하단의 프로젝트 목록에서도 권한에 관계없이 모든 프로젝트가 보이는 것 같습니다.
- 해당 스페이스에서 사용자 권한만 가진 계정(관리자 아님)으로 조회했을 때 나타나는 현상이라서, 의도된 동작인지 확인 부탁드립니다.

**Comment by mindplates** [comment]
항상 제보 감사합니다! 수정이 늦어져 죄송합니다.
- GNB에 프로젝트 목록을 노출하는 기능은 헤더 GNB이 너무 복잡해져서, 과거 릴리즈에서 제거되었습니다.
- 스페이스 정보에서 프로젝트 목록에 권한이 없는 프로젝트가 노출되는 버그를 수정하였습니다. (#127)
  - 다만, 스페이스 어드민 권한의 사용자의 경우에는 기존과 같이 스페이스의 모든 프로젝트가 조회됩니다.

**Comment by mindplates** [comment]
@scintillavoy 
v1.3.5 버전이 릴리즈되었습니다.
