### ISSUE TITLE
Slack으로 발송되는 테스트런 종료 메시지의 수치가 잘못 표시되는 문제

### ISSUE THREAD

**Issue by scintillavoy** [case-book/casebook#98]
- 테스트런이 종료되었을 때 Slack으로 발송되는 메시지에서 일부 수치가 잘못 표시됩니다.
- 다음 사진과 같이 테스트 진행률과 성공이 100%로 표시되지 않고 0%로 표시됩니다.
  <img width="170" alt="스크린샷 2023-05-16 23 37 51" src="https://github.com/case-book/casebook/assets/23258719/47831491-bd79-4027-8abd-fb9fb597647f">
- 테스트가 딱 한 개인 테스트런이 종료되었을 때 발생하는 문제인 것으로 추측됩니다.

**Comment by isangu** [comment]
[해당 PR](https://github.com/case-book/casebook/pull/110) 로 처리되었습니다~
